# Generated by Django 2.0.1 on 2018-01-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatsManagement', '0002_cat_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='birth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
